-- MySQL Script generated by MySQL Workbench
-- mar 19 abr 2016 10:18:49 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controlenvios
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `controlenvios` ;

-- -----------------------------------------------------
-- Schema controlenvios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlenvios` DEFAULT CHARACTER SET utf8 ;
USE `controlenvios` ;

-- -----------------------------------------------------
-- Table `controlenvios`.`mensajeria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlenvios`.`mensajeria` ;

CREATE TABLE IF NOT EXISTS `controlenvios`.`mensajeria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlenvios`.`origen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlenvios`.`origen` ;

CREATE TABLE IF NOT EXISTS `controlenvios`.`origen` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlenvios`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlenvios`.`departamento` ;

CREATE TABLE IF NOT EXISTS `controlenvios`.`departamento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlenvios`.`destinatario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlenvios`.`destinatario` ;

CREATE TABLE IF NOT EXISTS `controlenvios`.`destinatario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `f_departamento` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_destinatario_Departamento1_idx` (`f_departamento` ASC),
  CONSTRAINT `fk_destinatario_Departamento1`
    FOREIGN KEY (`f_departamento`)
    REFERENCES `controlenvios`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = dec8;


-- -----------------------------------------------------
-- Table `controlenvios`.`tiposusuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlenvios`.`tiposusuario` ;

CREATE TABLE IF NOT EXISTS `controlenvios`.`tiposusuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlenvios`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlenvios`.`usuario` ;

CREATE TABLE IF NOT EXISTS `controlenvios`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `f_tiposusuario` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`name` ASC),
  INDEX `fk_usuario_tiposusuario1_idx` (`f_tiposusuario` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_usuario_tiposusuario1`
    FOREIGN KEY (`f_tiposusuario`)
    REFERENCES `controlenvios`.`tiposusuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlenvios`.`guia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlenvios`.`guia` ;

CREATE TABLE IF NOT EXISTS `controlenvios`.`guia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `observacion` VARCHAR(45) NULL,
  `fecha` DATETIME NOT NULL,
  `otroorigen` VARCHAR(45) NULL,
  `otrodestinatario` VARCHAR(45) NULL,
  `f_origen` INT(11) NULL,
  `f_mensajeria` INT(11) NOT NULL,
  `f_destinatario` INT(11) NULL,
  `f_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Guia_origen1_idx` (`f_origen` ASC),
  INDEX `fk_Guia_mensajeria1_idx` (`f_mensajeria` ASC),
  INDEX `fk_Guia_destinatario1_idx` (`f_destinatario` ASC),
  INDEX `fk_guia_usuario1_idx` (`f_usuario` ASC),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC),
  CONSTRAINT `fk_Guia_origen1`
    FOREIGN KEY (`f_origen`)
    REFERENCES `controlenvios`.`origen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Guia_mensajeria1`
    FOREIGN KEY (`f_mensajeria`)
    REFERENCES `controlenvios`.`mensajeria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Guia_destinatario1`
    FOREIGN KEY (`f_destinatario`)
    REFERENCES `controlenvios`.`destinatario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_guia_usuario1`
    FOREIGN KEY (`f_usuario`)
    REFERENCES `controlenvios`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
