-- MySQL Script generated by MySQL Workbench
-- jue 14 abr 2016 10:53:30 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controlenvios
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `controlenvios` ;

-- -----------------------------------------------------
-- Schema controlenvios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlenvios` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `controlenvios` ;

-- -----------------------------------------------------
-- Table `controlenvios`.`mensajeria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlenvios`.`mensajeria` ;

CREATE TABLE IF NOT EXISTS `controlenvios`.`mensajeria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlenvios`.`origen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlenvios`.`origen` ;

CREATE TABLE IF NOT EXISTS `controlenvios`.`origen` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(30) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlenvios`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlenvios`.`departamento` ;

CREATE TABLE IF NOT EXISTS `controlenvios`.`departamento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlenvios`.`destinatario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlenvios`.`destinatario` ;

CREATE TABLE IF NOT EXISTS `controlenvios`.`destinatario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `f_departamento` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC)  COMMENT '',
  INDEX `fk_destinatario_Departamento1_idx` (`f_departamento` ASC)  COMMENT '',
  CONSTRAINT `fk_destinatario_Departamento1`
    FOREIGN KEY (`f_departamento`)
    REFERENCES `controlenvios`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = dec8
COLLATE = dec8_swedish_ci;


-- -----------------------------------------------------
-- Table `controlenvios`.`tiposusuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlenvios`.`tiposusuario` ;

CREATE TABLE IF NOT EXISTS `controlenvios`.`tiposusuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlenvios`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlenvios`.`usuario` ;

CREATE TABLE IF NOT EXISTS `controlenvios`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `f_tiposusuario` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `nombre_UNIQUE` (`name` ASC)  COMMENT '',
  INDEX `fk_usuario_tiposusuario1_idx` (`f_tiposusuario` ASC)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_tiposusuario1`
    FOREIGN KEY (`f_tiposusuario`)
    REFERENCES `controlenvios`.`tiposusuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlenvios`.`guia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlenvios`.`guia` ;

CREATE TABLE IF NOT EXISTS `controlenvios`.`guia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `numero` VARCHAR(45) NOT NULL COMMENT '',
  `observacion` VARCHAR(45) NULL COMMENT '',
  `fecha` DATETIME NOT NULL COMMENT '',
  `otroorigen` VARCHAR(45) NULL COMMENT '',
  `otrodestinatario` VARCHAR(45) NULL COMMENT '',
  `f_origen` INT(11) NULL COMMENT '',
  `f_mensajeria` INT(11) NOT NULL COMMENT '',
  `f_destinatario` INT(11) NULL COMMENT '',
  `f_usuario` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Guia_origen1_idx` (`f_origen` ASC)  COMMENT '',
  INDEX `fk_Guia_mensajeria1_idx` (`f_mensajeria` ASC)  COMMENT '',
  INDEX `fk_Guia_destinatario1_idx` (`f_destinatario` ASC)  COMMENT '',
  INDEX `fk_guia_usuario1_idx` (`f_usuario` ASC)  COMMENT '',
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC)  COMMENT '',
  CONSTRAINT `fk_Guia_origen1`
    FOREIGN KEY (`f_origen`)
    REFERENCES `controlenvios`.`origen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Guia_mensajeria1`
    FOREIGN KEY (`f_mensajeria`)
    REFERENCES `controlenvios`.`mensajeria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Guia_destinatario1`
    FOREIGN KEY (`f_destinatario`)
    REFERENCES `controlenvios`.`destinatario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_guia_usuario1`
    FOREIGN KEY (`f_usuario`)
    REFERENCES `controlenvios`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
