package mx.trillas.ControlEnvio.persistence.pojos;
// Generated 19/04/2016 10:31:08 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Guia generated by hbm2java
 */
public class Guia implements java.io.Serializable {

	/**
	*
	*/
	private static final long serialVersionUID = 1L;

	private Integer id;
	private Destinatario destinatario;
	private Mensajeria mensajeria;
	private Origen origen;
	private Usuario usuario;
	private String numero;
	private String observacion;
	private Date fecha;
	private String otroorigen;
	private String otrodestinatario;
	private String otrodepartamento;

	public Guia() {
	}

	public Guia(Mensajeria mensajeria, Usuario usuario, String numero, Date fecha) {
		this.mensajeria = mensajeria;
		this.usuario = usuario;
		this.numero = numero;
		this.fecha = fecha;
	}

	public Guia(Destinatario destinatario, Mensajeria mensajeria, Origen origen, Usuario usuario, String numero,
			String observacion, Date fecha, String otroorigen, String otrodestinatario, String otrodepartamento) {
		this.destinatario = destinatario;
		this.mensajeria = mensajeria;
		this.origen = origen;
		this.usuario = usuario;
		this.numero = numero;
		this.observacion = observacion;
		this.fecha = fecha;
		this.otroorigen = otroorigen;
		this.otrodestinatario = otrodestinatario;
		this.otrodepartamento = otrodepartamento;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Destinatario getDestinatario() {
		return this.destinatario;
	}

	public void setDestinatario(Destinatario destinatario) {
		this.destinatario = destinatario;
	}

	public Mensajeria getMensajeria() {
		return this.mensajeria;
	}

	public void setMensajeria(Mensajeria mensajeria) {
		this.mensajeria = mensajeria;
	}

	public Origen getOrigen() {
		return this.origen;
	}

	public void setOrigen(Origen origen) {
		this.origen = origen;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getOtroorigen() {
		return this.otroorigen;
	}

	public void setOtroorigen(String otroorigen) {
		this.otroorigen = otroorigen;
	}

	public String getOtrodestinatario() {
		return this.otrodestinatario;
	}

	public void setOtrodestinatario(String otrodestinatario) {
		this.otrodestinatario = otrodestinatario;
	}

	public String getOtrodepartamento() {
		return this.otrodepartamento;
	}

	public void setOtrodepartamento(String otrodepartamento) {
		this.otrodepartamento = otrodepartamento;
	}

	@Override
	public String toString() {
		return this.id + "";
	}
}
