package mx.trillas.ControlEnvio.persistence.pojos;
// Generated 18/04/2016 11:21:28 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Mensajeria generated by hbm2java
 */
public class Mensajeria  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set guias = new HashSet(0);

    public Mensajeria() {
    }

	
    public Mensajeria(String nombre) {
        this.nombre = nombre;
    }
    public Mensajeria(String nombre, Set guias) {
       this.nombre = nombre;
       this.guias = guias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getGuias() {
        return this.guias;
    }
    
    public void setGuias(Set guias) {
        this.guias = guias;
    }




}


