package mx.trillas.ControlEnvio.persistence.pojos;
// Generated 18/04/2016 11:21:28 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tiposusuario generated by hbm2java
 */
public class Tiposusuario  implements java.io.Serializable {


     private Integer id;
     private String tipo;
     private Set usuarios = new HashSet(0);

    public Tiposusuario() {
    }

	
    public Tiposusuario(String tipo) {
        this.tipo = tipo;
    }
    public Tiposusuario(String tipo, Set usuarios) {
       this.tipo = tipo;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


