package mx.trillas.RepartoPaqueteria.persistence.pojos;
// Generated 19/04/2016 10:31:08 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Tiposusuario generated by hbm2java
 */
public class Tiposusuario implements java.io.Serializable {
	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String tipo;
	private Set usuarios = new HashSet(0);

	public Tiposusuario() {
	}

	public Tiposusuario(String tipo) {
		this.tipo = tipo;
	}

	public Tiposusuario(String tipo, Set usuarios) {
		this.tipo = tipo;
		this.usuarios = usuarios;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (!(obj instanceof Tiposusuario))
			return false;

		Tiposusuario tiposusuario = (Tiposusuario) obj;

		if (this.id == tiposusuario.getId())
			return true;
		return false;
	}
}
